project:
  type: website

website:
  title: "Lou Chiani"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: files/CV_Lou_Chiani.pdf
        text: CV
        target: _blank

format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    anchor-links: false
